import os
import base64
import re
import torch
import asyncio
from concurrent.futures import ThreadPoolExecutor
import concurrent.futures
from typing import Dict, List, Optional

from swift.rewards import ORM, orms
from swift.rollout.multi_turn import MultiTurnScheduler, multi_turns, remove_response

from mycom_env import mycom_envs, mycom_env_queue


import sys
from swift.utils import get_logger
logger = get_logger()

# ---------------------------------------------------------------------------
# Constants & Utility Functions
# ---------------------------------------------------------------------------

def _extract_py_code(text: str) -> Optional[str]:
    """Extract the last ```python``` block"""
    matches = re.findall(r'```python\s*(.*?)\s*```', text, re.DOTALL)
    if matches:
        return matches[-1].strip()
    else:
        return None

def _extract_decision(text: str) -> Optional[str]:
    """Extract the last ```decision``` block"""
    matches = re.findall(r'```decision\s*(.*?)\s*```', text, re.DOTALL)
    if matches:
        return matches[-1].strip()
    else:
        return None

# ---------------------------------------------------------------------------
# 1. Multi-Turn Scheduler
# ---------------------------------------------------------------------------

class COMMultiTurnScheduler(MultiTurnScheduler):

    def check_finished(self, infer_request, response_choice, current_turn: int) -> bool:
        content = response_choice.message.content or ""
        
        decision = _extract_decision(content)
        
        if decision and ('DONE' in decision.upper() or 'FAIL' in decision.upper()):
            return True

        return super().check_finished(infer_request, response_choice, current_turn)


    def step(self, infer_request, response_choice, current_turn: int) -> Dict:
        content = response_choice.message.content or ""

        def _run_env_sync():
            """Closure to run async virtual machines in a synchronous function"""
            loop = asyncio.new_event_loop()
            loop.set_default_executor(ThreadPoolExecutor(max_workers=256))
            # asyncio.set_event_loop(loop)
            
            try:
                # ==========================================
                # State Machine: Turn 1, Reset then Step
                # ==========================================
                if current_turn == 1:
                    # 1. Fetch the exclusive VM assigned to the current task from the queue manager
                    env_id = mycom_env_queue.get()

                    infer_request.data_dict['env_id'] = env_id
                    env = mycom_envs[str(env_id)]
                    env.task_config = infer_request.data_dict
                    
                    # 2. Reset the environment (equivalent to clearing files and opening CAD software)
                    loop.run_until_complete(env.reset(infer_request))
                    
                    # 3. Immediately execute the first code block generated by the LLM
                    next_obs, reward, terminated, done, fail, step_info = loop.run_until_complete(env.step(content))
                    return env_id, next_obs
                
                # ==========================================
                # State Machine: Subsequent Turns, Step Directly
                # ==========================================
                else:
                    env_id = infer_request.data_dict['env_id']
                    env = mycom_envs[str(env_id)]
                    
                    # Execute the newly generated code directly
                    next_obs, reward, terminated, done, fail, step_info = loop.run_until_complete(env.step(content))
                    return env_id, next_obs
                    
            finally:
                loop.close()
                
        # 1. Run environment interaction (retrieve VM ID and latest screenshot)
        env_id, next_obs = _run_env_sync()
        
        # 2. Get the current conversation history
        messages = infer_request.messages
        
        # 3. Seal the envelope! Append the VM ID to the end of the model's response (for the Reward function to locate it)
        stamp = f"\n[ENV_ID:{env_id}]"
        # messages.append({'role': 'assistant', 'content': content + stamp})
        if messages[-1]['role'] == 'assistant':
            messages[-1]['content'] = messages[-1]['content']+stamp
        # response_choice.message.content = content + stamp
        
        terminal_output = next_obs.get('terminal', {})
        screenshot = next_obs.get('screenshot', b'')
        img_b64_str = base64.b64encode(screenshot).decode('utf-8') if screenshot else ""
        
        if screenshot:
            import time
            sample_id = infer_request.data_dict.get('id', 'unknown')
            rank = os.environ.get('RANK', '0')
            timestamp = time.strftime('%m%d_%H%M%S')
            # Save the latest CAD screenshot to the local server
            img_path = f"/nvme/aijiaxin/cache/msswift/screenshot/com_env{env_id}_turn{current_turn}_sample{sample_id}_rank{rank}_timestamp{timestamp}.png"

            with open(img_path, "wb") as f:
                f.write(screenshot)
            infer_request.images.append(img_path)
            
            messages.append({
                "role": "user",
                "content": f"- Current Screenshot: <image>\n- Previous Terminal output: {terminal_output}"
            })
        else:
            messages.append({
                "role": "user",
                "content": f"- Previous Terminal output: {terminal_output}"
            })

        return {"infer_request": infer_request}



multi_turns["com_scheduler"] = COMMultiTurnScheduler


# ---------------------------------------------------------------------------
# 2. Reward Function
# ---------------------------------------------------------------------------

class COMChamferReward(ORM):
    """
    Global reward calculation class specifically for COM tasks.
    Responsible for receiving LLM outputs, matching virtual machines, 
    downloading and verifying CAD physical Chamfer Distance.
    """

    def _evaluate_single(self, msg_list) -> float:
        """
        Single-sample scoring logic invoked by the thread pool.
        """
        reward_score = 0.0
        env_id = None
        
        try:
            # ==========================================
            # 1. Get the last message (used to determine if it is a FAIL)
            # ==========================================
            last_content = ""
            for msg in reversed(msg_list):
                if msg.get("role") == "assistant":
                    last_content = msg.get("content", "")
                    if isinstance(last_content, list):
                        last_content = " ".join(c.get("text", "") for c in last_content if c.get("type") == "text")
                    break  # Break once the last message is found
            
            # ==========================================
            # 2. Search backward for the environment ID stamp (as the last sentence might be an unsealed DONE)
            # ==========================================
            for msg in reversed(msg_list):
                if msg.get("role") == "assistant":
                    content_str = msg.get("content", "")
                    if isinstance(content_str, list):
                        content_str = " ".join(c.get("text", "") for c in content_str if c.get("type") == "text")
                    
                    match = re.search(r'\[ENV_ID:\s*(\d+)\]', content_str)
                    if match:
                        env_id = int(match.group(1))
                        break  # Found the actual stamped ID, break the search loop

            # If no ID stamp is found across the history (implies a crash before code generation in Turn 1)
            if env_id is None:
                return 0.0
                
            env = mycom_envs[str(env_id)]
            
            # ==========================================
            # 3. Reward Calculation Logic
            # ==========================================
            decision = _extract_decision(last_content)
            if decision and 'FAIL' in decision.upper():
                reward_score = 0.0
            else:
                task_type = env.task_config.get('task_type', '')
                if task_type in ['3d_model', 'assembly']:
                    reward_score, _ = env.evaluate_3d_model()
                elif task_type == '2d_sketch':
                    reward_score, _ = env.evaluate_2d_sketch()
                else:
                    reward_score = 0.0
                    
        except Exception as e:
            logger.error(f"Evaluation Error: {e}")
            reward_score = 0.0
            
        finally:
            # Fallback to 0.0 score for any exceptions
            if env_id is not None:
                mycom_env_queue.put(env_id)
                
        return reward_score


    def __call__(self, completions, messages, **kwargs) -> List[float]:
        # ==============================================================
        # High-speed concurrent launch via ThreadPoolExecutor!
        # Set max_workers to len(messages) to ensure an independent thread for each data sample.
        # ==============================================================
        with concurrent.futures.ThreadPoolExecutor(max_workers=len(messages)) as executor:
            rewards = list(executor.map(self._evaluate_single, messages))
            
        return rewards


orms["com_reward"] = COMChamferReward